name: walking-through
slug: walking-through
version: 1.0.0
description: |
  Use this skill IF user needs to manually test a user journey,
  OR wants to validate flows against live application,
  OR is capturing gaps during testing,
  OR needs to verify implementation against expectations.
  Provides guided interactive walkthrough with agent-browser and automatic gap documentation.

# Trigger patterns - when this skill should activate
triggers:
  - "/walkthrough"
  - "test this journey manually"
  - "walk through the flow"
  - "validate against live app"
  - "manual test"
  - "check the journey"
  - "step through this"

# Natural language examples for intent matching
examples:
  - context: "User wants to test deposit flow"
    user_says: "Can you walk me through testing the deposit journey?"
    agent_action: "Launch walking-through to start guided browser session with step-by-step validation"
  - context: "User found a gap and wants to document it"
    user_says: "I want to test the rewards flow and capture any issues"
    agent_action: "Launch walking-through to execute journey with automatic gap discovery capture"
  - context: "User testing with specific wallet state"
    user_says: "Test the migration flow with a rewards-ready wallet"
    agent_action: "Launch walking-through with --wallet test-rewards-ready to use specific test wallet"
  - context: "User verifying fix implementation"
    user_says: "I want to verify the fix worked, walk through step 3 onwards"
    agent_action: "Launch walking-through with --step 3 to start validation from specific step"

# Domain hints for proactive suggestion
domain_hints:
  - testing
  - manual
  - walkthrough
  - validation
  - journey
  - browser
  - interactive

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: moderate
  effort_hint: large
  downgrade_allowed: false
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: false
    vision: true

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
  - Bash
  - Skill
