name: next-best-practices
slug: next-best-practices
version: 1.0.0
description: React and Next.js performance optimization patterns from Vercel Engineering

# Trigger patterns - when this skill should activate
triggers:
  - "/next"
  - "optimize performance"
  - "bundle size issue"
  - "slow page load"
  - "react optimization"
  - "nextjs best practice"
  - "waterfall requests"

# Natural language examples for intent matching
examples:
  - context: "User experiencing slow page loads"
    user_says: "This page is loading slowly due to sequential data fetching"
    agent_action: "Launch next-best-practices to identify waterfall patterns and apply Promise.all parallelization"
  - context: "User reviewing bundle size"
    user_says: "Bundle size is too large from component imports"
    agent_action: "Launch next-best-practices to check for barrel imports and apply next/dynamic for heavy components"
  - context: "User implementing data fetching"
    user_says: "Should I use React.cache for this server component?"
    agent_action: "Launch next-best-practices to evaluate request deduplication needs and apply React.cache pattern"
  - context: "User optimizing re-renders"
    user_says: "This component re-renders too often"
    agent_action: "Launch next-best-practices to apply memo, functional setState, and startTransition patterns"

# Domain hints for proactive suggestion
domain_hints:
  - nextjs
  - react
  - performance
  - optimization
  - bundle
  - waterfall
  - suspense
  - caching

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: moderate
  effort_hint: medium
  downgrade_allowed: true
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: false
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
