name: inscribing-taste
slug: inscribing-taste
version: 1.0.0
description: Apply brand taste tokens to components from taste.md

# Trigger patterns - when this skill should activate
triggers:
  - "/inscribe"
  - "apply brand tokens"
  - "use design system"
  - "match brand style"
  - "apply taste"
  - "brand compliance"
  - "style tokens"

# Natural language examples for intent matching
examples:
  - context: "User implementing new button"
    user_says: "Apply our brand styling to this Button component"
    agent_action: "Launch inscribing-taste to read taste.md and apply color, typography, spacing, and motion tokens"
  - context: "User reviewing component"
    user_says: "Does this Card match our design system?"
    agent_action: "Launch inscribing-taste to validate component against taste.md tokens and direction.md constraints"
  - context: "User building feature"
    user_says: "What shadow should I use for this elevated panel?"
    agent_action: "Launch inscribing-taste to reference taste.md shadow tokens and apply appropriate elevation"
  - context: "User applying gradient"
    user_says: "Want to add a gradient background here"
    agent_action: "Launch inscribing-taste to check direction.md 'We Avoid' constraints and suggest alternative if conflicts"

# Domain hints for proactive suggestion
domain_hints:
  - brand
  - taste
  - tokens
  - design-system
  - style
  - consistency
  - theme
  - direction

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: moderate
  effort_hint: medium
  downgrade_allowed: false
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: false
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
