name: crafting-physics
slug: crafting-physics
version: 1.0.0
description: Design physics system for UI interactions - sync strategies, timing, confirmations
entry: SKILL.md
triggers:
  - /physics
allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
