name: decomposing-feel
slug: decomposing-feel
version: 1.2.0
description: |
  Use this skill IF user gives vague design feedback like "something's off",
  OR can't articulate what's wrong with the design,
  OR needs help identifying specific issues from a general feeling.
  Converts vague feedback into actionable fixes through guided decomposition.

# Trigger patterns - when this skill should activate
triggers:
  - "/decompose"
  - "something's off"
  - "doesn't feel right"
  - "can't put my finger on it"
  - "not quite right"
  - "something feels wrong"
  - "help me identify what's off"
  - "vague feedback"
  - "feels weird"

# Natural language examples for intent matching
examples:
  - context: "User can't articulate the issue"
    user_says: "The card doesn't feel right but I can't say why"
    agent_action: "Launch decomposing-feel to guide user through dimension identification"
  - context: "Vague feedback during iteration"
    user_says: "Something's off about this button"
    agent_action: "Launch decomposing-feel to decompose feedback into spacing/color/hierarchy/motion"
  - context: "User knows something is wrong"
    user_says: "It's close but not quite there"
    agent_action: "Launch decomposing-feel with A/B comparison to identify the gap"
  - context: "General dissatisfaction"
    user_says: "I don't like how this looks but I'm not sure what to change"
    agent_action: "Launch decomposing-feel to systematically identify the problematic dimension"

# Domain hints for proactive suggestion
domain_hints:
  - design
  - feedback
  - ui
  - ux
  - feel
  - aesthetic

entry: SKILL.md

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
  - AskUserQuestion

dependencies:
  - artifact: "grimoires/artisan/taste.md"
    required: false
    description: "Project taste tokens for grounded resolution"

outputs:
  - path: "grimoires/artisan/feedback/*.jsonl"
    description: "Decomposition logs for pattern detection"
