name: rams
slug: rams
version: 1.0.0
description: Accessibility and visual design review based on WCAG 2.1

# Trigger patterns - when this skill should activate
triggers:
  - "/rams"
  - "accessibility review"
  - "check for a11y issues"
  - "wcag compliance"
  - "audit accessibility"
  - "missing alt text"
  - "focus outline issues"

# Natural language examples for intent matching
examples:
  - context: "User submitting component for review"
    user_says: "Can you check this component for accessibility issues?"
    agent_action: "Launch rams to audit for WCAG 2.1 compliance including alt text, aria-labels, and keyboard navigation"
  - context: "User implementing icon button"
    user_says: "Is this icon-only button accessible?"
    agent_action: "Launch rams to verify aria-label presence and proper semantic markup"
  - context: "User building form"
    user_says: "Review this form for accessibility"
    agent_action: "Launch rams to check label associations, input types, and error message placement"
  - context: "User debugging focus issues"
    user_says: "Focus outline isn't visible when I removed outline-none"
    agent_action: "Launch rams to verify focus-visible replacement and suggest proper focus ring implementation"

# Domain hints for proactive suggestion
domain_hints:
  - accessibility
  - a11y
  - wcag
  - aria
  - semantic
  - keyboard
  - screen-reader
  - audit

entry: SKILL.md

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
  - Bash
