name: iterating-feedback
slug: iterating-feedback
version: 1.0.0
description: |
  Use this skill IF test results need to be traced back to upstream artifacts,
  OR user wants to add visual gaps from Agentation annotations,
  OR test failures need root cause analysis across canvases/journeys/diagrams.
  Closes the feedback loop by updating upstream artifacts from test results.

# Trigger patterns - when this skill should activate
triggers:
  - "/iterate"
  - "trace test failures to upstream"
  - "update canvases from test results"
  - "add gap from visual testing"
  - "close the feedback loop"
  - "what broke and why"
  - "map failures to journeys"

# Natural language examples for intent matching
examples:
  - context: "Test failures exist and need root cause analysis"
    user_says: "The deposit-flow tests are failing, can you trace back to the journey?"
    agent_action: "Launch iterating-feedback to classify failures and map to upstream canvases/journeys"
  - context: "Visual gap discovered during testing"
    user_says: "I found a spinner that persists after completion, add it as a gap"
    agent_action: "Launch iterating-feedback with --add-gap to document gap in canvas and journey"
  - context: "User wants to apply proposed upstream fixes"
    user_says: "Apply the proposed changes from the feedback analysis"
    agent_action: "Launch iterating-feedback with --apply to update canvases, journeys, and diagrams"
  - context: "User annotated UI issue via Agentation"
    user_says: "I annotated the broken element, add it as a gap for this journey"
    agent_action: "Launch iterating-feedback with --annotate to fetch Agentation annotations as gaps"

# Domain hints for proactive suggestion
domain_hints:
  - feedback-loop
  - test-results
  - root-cause
  - upstream-artifacts
  - canvas
  - journey
  - gap-tracking
  - regression

entry: SKILL.md

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit

integrations:
  optional:
    - name: "agentation"
      scopes: [agentation_get_all_pending, agentation_resolve]
      reason: "Fetch visual annotations as gap evidence"
      fallback: "Manual --add-gap with text description"
