name: "reviewing-gtm"
version: "1.0.0"
model: "sonnet"
color: "red"

description: |
  Use this skill IF user invokes `/review-gtm` OR needs GTM strategy review,
  consistency check, or gap analysis.

  Reviews all GTM artifacts for consistency and produces review report
  at `gtm-grimoire/a2a/reviews/`.

triggers:
  - "/review-gtm"
  - "review gtm strategy"
  - "check gtm consistency"
  - "gtm gap analysis"
  - "is my gtm ready"

examples:
  - context: "All GTM docs complete"
    user_says: "/review-gtm"
    agent_action: |
      1. Read all GTM artifacts
      2. Check cross-document consistency
      3. Identify gaps
      4. Validate against product reality
      5. Produce review verdict

domain_hints:
  - GTM strategy review
  - launch readiness
  - consistency check
  - gap analysis
  - strategy validation
  - GTM assessment
  - pre-launch review
  - execution readiness

inputs:
  - name: "research_dir"
    type: "directory"
    path: "gtm-grimoire/research/"
    required: true
  - name: "strategy_dir"
    type: "directory"
    path: "gtm-grimoire/strategy/"
    required: true
  - name: "execution_dir"
    type: "directory"
    path: "gtm-grimoire/execution/"
    required: false

outputs:
  - path: "gtm-grimoire/a2a/reviews/gtm-review-{date}.md"
    description: "Review report with verdict"

dependencies:
  - artifact: "gtm-grimoire/research/"
    optional: false
    purpose: "Research to review"
  - artifact: "gtm-grimoire/strategy/"
    optional: false
    purpose: "Strategy to review"

protocols:
  required:
    - name: "session-continuity"
      path: ".claude/protocols/session-continuity.md"
    - name: "grounding-enforcement"
      path: ".claude/protocols/grounding-enforcement.md"

pack:
  id: "gtm-collective"
  requires_subscription: true

parallel_execution:
  enabled: false
