name: bridgebuilder-review
slug: bridgebuilder-review
version: 1.0.0
description: |
  Multi-persona adversarial review of pack outputs using Physics of Error
  vocabulary. Detects Near Misses and Category Errors in generated artifacts.
  Requires midi-interface runtime for full orchestration.

triggers:
  - "/bridgebuilder-review"
  - "review with bridgebuilder"
  - "run taste review"
  - "run research review"
  - "run strategy review"
  - "check for near misses"
  - "detect category errors"

examples:
  - context: "User wants design system compliance check"
    user_says: "Review this component for taste compliance"
    agent_action: "Launch bridgebuilder-review with taste persona to detect token violations"
  - context: "User wants research methodology check"
    user_says: "Check if this canvas follows Mom Test principles"
    agent_action: "Launch bridgebuilder-review with research persona to detect methodology violations"

domain_hints:
  - review
  - quality
  - adversarial
  - near-miss
  - category-error
  - physics-of-error
  - compliance

entry: SKILL.md

capabilities:
  model_tier: opus
  danger_level: moderate
  effort_hint: large
  downgrade_allowed: false
  execution_hint: sequential
  requires:
    native_runtime: false
    tool_calling: true
    thinking_traces: required
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
