name: "educating-developers"
version: "1.0.0"
model: "sonnet"
color: "cyan"

description: |
  Use this skill IF user invokes `/plan-devrel` OR needs developer relations
  strategy, documentation plan, or community building.

  Produces DevRel strategy at `gtm-grimoire/strategy/devrel-strategy.md`.

triggers:
  - "/plan-devrel"
  - "developer relations"
  - "devrel strategy"
  - "documentation strategy"
  - "community building"
  - "developer advocacy"
  - "developer education"

examples:
  - context: "Positioning complete"
    user_says: "/plan-devrel"
    agent_action: |
      1. Read positioning and ICP profiles
      2. Design documentation strategy
      3. Plan community building
      4. Create content roadmap
      5. Generate devrel-strategy.md
  - context: "Low developer adoption due to documentation gaps"
    user_says: "How do we improve developer engagement?"
    agent_action: |
      1. Review positioning, ICP profiles, and market analysis
      2. Design API docs, tutorials, and SDK guides
      3. Plan community initiatives like Discord, forums, and meetups
      4. Create 12-month developer education roadmap
      5. Define success metrics for adoption and community growth

domain_hints:
  - developer relations
  - developer education
  - documentation strategy
  - developer advocacy
  - community building
  - technical tutorials
  - API documentation
  - developer community

inputs:
  - name: "positioning"
    type: "file"
    path: "gtm-grimoire/strategy/positioning.md"
    required: true
  - name: "icp_profiles"
    type: "file"
    path: "gtm-grimoire/research/icp-profiles.md"
    required: true

outputs:
  - path: "gtm-grimoire/strategy/devrel-strategy.md"
    description: "Documentation, community, advocacy strategy"

dependencies:
  - artifact: "gtm-grimoire/strategy/positioning.md"
    optional: false
    purpose: "Align DevRel with positioning"

protocols:
  required:
    - name: "session-continuity"
      path: ".claude/protocols/session-continuity.md"
    - name: "grounding-enforcement"
      path: ".claude/protocols/grounding-enforcement.md"

pack:
  id: "gtm-collective"
  requires_subscription: true

capabilities:
  model_tier: sonnet
  danger_level: safe
  effort_hint: medium
  downgrade_allowed: true
  execution_hint: sequential
  requires:
    native_runtime: false
    tool_calling: true
    thinking_traces: false
    vision: false

parallel_execution:
  enabled: false
