name: defining-actions
slug: defining-actions
version: 1.0.0
description: Generate JSON Schema and OpenAPI specs for x402 endpoints

# Trigger patterns - when this skill should activate
triggers:
  - "/beacon-actions"
  - "generate schema for payment endpoints"
  - "create OpenAPI spec for x402"
  - "define action schemas"
  - "make endpoints machine-readable"
  - "generate JSON Schema for API"
  - "document payment-enabled routes"

# Natural language examples for intent matching
examples:
  - context: "User wants agents to understand API"
    user_says: "How do AI agents know what parameters my generate-image endpoint accepts?"
    agent_action: "Launch defining-actions to generate JSON Schema and OpenAPI spec for the endpoint"
  - context: "User building type-safe API"
    user_says: "Generate schemas for all my x402 endpoints so agents can validate requests"
    agent_action: "Launch defining-actions to analyze route handlers and create machine-readable specifications"
  - context: "User improving discoverability"
    user_says: "I need OpenAPI docs for my payment-enabled API"
    agent_action: "Launch defining-actions to generate combined OpenAPI spec with x-payment extensions"

# Domain hints for proactive suggestion
domain_hints:
  - json-schema
  - openapi
  - api-spec
  - machine-readable
  - type-safety
  - x402
  - agent-actions
  - schema-generation

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: moderate
  effort_hint: medium
  downgrade_allowed: false
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: false
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit

categories:
  - operations

inputExamples:
  - "/beacon-actions"
  - "/beacon-actions /api/generate-image"

outputs:
  - name: action-schemas
    path: "app/api/*/schema.json"
    format: detailed
  - name: openapi-fragment
    path: "grimoires/beacon/discovery/openapi.yaml"
    format: detailed
