name: generating-markdown
slug: generating-markdown
version: 1.0.0
description: Add markdown export capability to Next.js pages via content negotiation and/or copy button. Detects codebase patterns to generate tailored code.

# Trigger patterns - when this skill should activate
triggers:
  - "/add-markdown"
  - "add markdown export to this page"
  - "make this page AI-readable"
  - "generate markdown endpoint"
  - "add copy button for markdown"
  - "enable content negotiation"
  - "serve this as markdown"

# Natural language examples for intent matching
examples:
  - context: "User wants AI agents to access content"
    user_says: "How can I make my pricing page available as markdown for AI agents?"
    agent_action: "Launch generating-markdown to add content negotiation and copy button to pricing page"
  - context: "User building AI-first API"
    user_says: "Add markdown export to all my documentation pages"
    agent_action: "Launch generating-markdown to generate route handlers with Accept: text/markdown support"
  - context: "User improving discoverability"
    user_says: "I need a copy button so users can share this page in markdown format"
    agent_action: "Launch generating-markdown in component-only mode to add copy markdown button"

# Domain hints for proactive suggestion
domain_hints:
  - markdown
  - content-negotiation
  - ai-export
  - agent-readable
  - copy-button
  - api-routes
  - text-format
  - discoverability

entry: SKILL.md

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
