name: "translating-for-stakeholders"
version: "1.0.0"
model: "sonnet"
color: "gold"

description: |
  Use this skill IF user invokes `/create-deck` OR needs pitch deck,
  investor presentation, or executive summary.

  Produces stakeholder-ready artifacts at `gtm-grimoire/execution/`.

triggers:
  - "/create-deck"
  - "pitch deck"
  - "investor deck"
  - "executive summary"
  - "board presentation"
  - "stakeholder presentation"

examples:
  - context: "GTM review approved"
    user_says: "/create-deck"
    agent_action: |
      1. Read all GTM strategy docs
      2. Synthesize key messages
      3. Create pitch deck content
      4. Generate pitch-deck.md
  - context: "Raising Series A with 12-slide limit for investors"
    user_says: "Create an investor pitch deck for our Series A round"
    agent_action: |
      1. Extract core value proposition and market opportunity from positioning
      2. Translate unit economics and GTM strategy into business metrics
      3. Build 12-slide narrative covering problem, solution, market, and ask
      4. Create executive summary of financial projections
      5. Generate pitch-deck.md with speaker notes for each slide

domain_hints:
  - pitch deck
  - investor presentation
  - executive communication
  - stakeholder communication
  - business translation
  - technical translation
  - board presentation
  - fundraising pitch

inputs:
  - name: "positioning"
    type: "file"
    path: "gtm-grimoire/strategy/positioning.md"
    required: true
  - name: "pricing"
    type: "file"
    path: "gtm-grimoire/strategy/pricing-strategy.md"
    required: true
  - name: "launch_plan"
    type: "file"
    path: "gtm-grimoire/execution/launch-plan.md"
    required: false

outputs:
  - path: "gtm-grimoire/execution/pitch-deck.md"
    description: "Pitch deck content with slide-by-slide breakdown"

dependencies:
  - artifact: "gtm-grimoire/strategy/positioning.md"
    optional: false
    purpose: "Core messaging for deck"
  - artifact: "gtm-grimoire/strategy/pricing-strategy.md"
    optional: false
    purpose: "Business model for deck"

protocols:
  required:
    - name: "session-continuity"
      path: ".claude/protocols/session-continuity.md"
    - name: "grounding-enforcement"
      path: ".claude/protocols/grounding-enforcement.md"

pack:
  id: "gtm-collective"
  requires_subscription: true

capabilities:
  model_tier: sonnet
  danger_level: safe
  effort_hint: small
  downgrade_allowed: true
  execution_hint: sequential
  requires:
    native_runtime: false
    tool_calling: true
    thinking_traces: false
    vision: false

parallel_execution:
  enabled: false
