name: "analyzing-market"
version: "1.0.0"
model: "sonnet"
color: "purple"

description: |
  Use this skill IF user invokes `/analyze-market` OR needs market research,
  competitive analysis, TAM/SAM/SOM sizing, or ICP development.

  Produces research artifacts to `gtm-grimoire/research/`:
  - market-landscape.md
  - competitive-analysis.md
  - icp-profiles.md

triggers:
  - "/analyze-market"
  - "market research"
  - "competitive analysis"
  - "market sizing"
  - "TAM SAM SOM"
  - "ideal customer profile"
  - "ICP"
  - "analyze the market"
  - "who are our competitors"

examples:
  - context: "GTM context exists"
    user_says: "/analyze-market"
    agent_action: |
      1. Read gtm-grimoire/context/product-brief.md or product-reality.md
      2. Research market using web search if available
      3. Produce market-landscape.md with TAM/SAM/SOM
      4. Produce competitive-analysis.md with feature matrix
      5. Produce icp-profiles.md with persona definitions

  - context: "No GTM context"
    user_says: "/analyze-market"
    agent_action: |
      1. Check for existing product context
      2. If missing, suggest /gtm-setup or /gtm-adopt first
      3. Proceed with available information

domain_hints:
  - market research
  - competitive analysis
  - TAM SAM SOM
  - market sizing
  - ideal customer profile
  - customer segmentation
  - market trends
  - industry landscape

inputs:
  - name: "product_context"
    type: "file"
    path: "gtm-grimoire/context/product-brief.md"
    required: false
  - name: "product_reality"
    type: "file"
    path: "gtm-grimoire/context/product-reality.md"
    required: false

outputs:
  - path: "gtm-grimoire/research/market-landscape.md"
    description: "TAM/SAM/SOM, trends, growth drivers"
  - path: "gtm-grimoire/research/competitive-analysis.md"
    description: "Feature matrix, pricing comparison, positioning gaps"
  - path: "gtm-grimoire/research/icp-profiles.md"
    description: "Ideal Customer Profiles with personas"

dependencies:
  - artifact: "gtm-grimoire/context/product-brief.md"
    optional: true
    purpose: "Ground research in product capabilities"
  - artifact: "gtm-grimoire/context/product-reality.md"
    optional: true
    purpose: "Understand actual product features"

protocols:
  required:
    - name: "session-continuity"
      path: ".claude/protocols/session-continuity.md"
    - name: "grounding-enforcement"
      path: ".claude/protocols/grounding-enforcement.md"
  recommended:
    - name: "trajectory-evaluation"
      path: ".claude/protocols/trajectory-evaluation.md"

pack:
  id: "gtm-collective"
  requires_subscription: true

capabilities:
  model_tier: sonnet
  danger_level: safe
  effort_hint: medium
  downgrade_allowed: true
  execution_hint: sequential
  requires:
    native_runtime: false
    tool_calling: true
    thinking_traces: false
    vision: false

parallel_execution:
  enabled: false
