name: "positioning-product"
version: "1.0.0"
model: "sonnet"
color: "blue"

description: |
  Use this skill IF user invokes `/position` OR needs product positioning,
  messaging framework, or differentiation strategy.

  Produces positioning strategy at `gtm-grimoire/strategy/positioning.md`.

triggers:
  - "/position"
  - "product positioning"
  - "messaging framework"
  - "value proposition"
  - "differentiation"
  - "how should we position"
  - "what's our positioning"

examples:
  - context: "Market research complete"
    user_says: "/position"
    agent_action: |
      1. Read gtm-grimoire/research/ artifacts
      2. Synthesize positioning framework
      3. Create messaging hierarchy
      4. Generate positioning.md
  - context: "Need to differentiate from 3 direct competitors in platform market"
    user_says: "How should we position ourselves?"
    agent_action: |
      1. Analyze competitive positioning and market landscape
      2. Identify unique value through ICP needs analysis
      3. Define positioning statement and core pillars
      4. Create messaging for different buyer personas
      5. Build brand narrative that resonates with target segments

domain_hints:
  - product positioning
  - messaging framework
  - value proposition
  - differentiation strategy
  - market positioning
  - brand messaging
  - competitive positioning
  - target audience messaging

inputs:
  - name: "market_landscape"
    type: "file"
    path: "gtm-grimoire/research/market-landscape.md"
    required: true
  - name: "competitive_analysis"
    type: "file"
    path: "gtm-grimoire/research/competitive-analysis.md"
    required: true
  - name: "icp_profiles"
    type: "file"
    path: "gtm-grimoire/research/icp-profiles.md"
    required: true

outputs:
  - path: "gtm-grimoire/strategy/positioning.md"
    description: "Positioning statement, messaging framework, differentiation"

dependencies:
  - artifact: "gtm-grimoire/research/market-landscape.md"
    optional: false
    purpose: "Market context for positioning"
  - artifact: "gtm-grimoire/research/competitive-analysis.md"
    optional: false
    purpose: "Competitive differentiation"
  - artifact: "gtm-grimoire/research/icp-profiles.md"
    optional: false
    purpose: "Target audience for messaging"

protocols:
  required:
    - name: "session-continuity"
      path: ".claude/protocols/session-continuity.md"
    - name: "grounding-enforcement"
      path: ".claude/protocols/grounding-enforcement.md"

pack:
  id: "gtm-collective"
  requires_subscription: true

parallel_execution:
  enabled: false
