name: distilling-components
slug: distilling-components
version: 1.0.0
description: Component design patterns - compound components, composition, props API
entry: SKILL.md
triggers:
  - /distill
allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
