name: synthesizing-taste
slug: synthesizing-taste
version: 1.0.0
description: Extract brand taste tokens from reference materials into taste.md
entry: SKILL.md
triggers:
  - /synthesize
allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
