name: analyzing-gaps
slug: analyzing-gaps
version: 1.0.0
description: Compare user expectations (UTCs) with code reality to identify gaps.

# Trigger patterns - when this skill should activate
triggers:
  - "/analyze-gap"
  - "compare expectations with reality"
  - "find gaps in user journey"
  - "what's the mismatch between user expectations and code"
  - "identify expectation gaps"
  - "analyze journey discrepancies"

# Natural language examples for intent matching
examples:
  - context: "Journey exists and needs gap analysis"
    user_says: "What are the gaps between what users expect and what the code does for rewards?"
    agent_action: "Launch analyzing-gaps for reward-understanding journey to compare UTC expectations with reality files"
  - context: "User wants to understand specific journey issues"
    user_says: "Analyze the deposit-flow journey for expectation gaps"
    agent_action: "Launch analyzing-gaps with journey-id deposit-flow to generate structured gap report"
  - context: "Need to prioritize fixes based on severity"
    user_says: "Show me high-severity gaps in the informed-decision journey"
    agent_action: "Launch analyzing-gaps with --severity-threshold high to filter critical issues"
  - context: "After creating reality file, need to compare with user truth"
    user_says: "Compare the use-recipe-deposit-flow reality with user expectations"
    agent_action: "Launch analyzing-gaps with --reality use-recipe-deposit-flow to analyze specific component"

# Domain hints for proactive suggestion
domain_hints:
  - gap-analysis
  - expectation-mismatch
  - utc
  - reality
  - discrepancy
  - severity
  - jtbd-impact
  - user-truth

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: moderate
  effort_hint: large
  downgrade_allowed: false
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: required
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
