name: managing-constructs
version: 1.0.0
description: Manage Forge packs in the Loa Constructs Registry
author: forge

trigger:
  pattern: /manage-constructs
  aliases:
    - /constructs
    - /packs

categories:
  - operations

effort_hint: medium
danger_level: moderate

inputs:
  - name: action
    description: |
      Operation to perform:
      - list: View current pack status
      - upload: Upload new/updated pack versions
      - submit: Submit packs for review
      - approve: Admin approve pending packs
      - publish: Full pipeline (upload → submit → approve)
    required: false
    default: interactive
  - name: packs
    description: Pack slugs to operate on (comma-separated)
    required: false

outputs:
  - name: result
    description: Operation result with status for each pack
    format: summary

inputExamples:
  - description: List all packs with status
    input: /manage-constructs list
  - description: Interactive mode (default)
    input: /manage-constructs
  - description: Upload specific pack
    input: /manage-constructs upload llm-ready
  - description: Full publish pipeline for multiple packs
    input: /manage-constructs publish observer,artisan

allowed-tools:
  - Bash
  - Read
  - AskUserQuestion

environment:
  required:
    - LOA_CONSTRUCTS_API_KEY
  optional:
    - LOA_CONSTRUCTS_ADMIN_KEY
