name: styling-material
slug: styling-material
version: 1.0.0
description: UI polish patterns for typography, visual design, layout, and dark mode
entry: SKILL.md
triggers:
  - /style
allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
