name: accepting-payments
slug: accepting-payments
version: 1.0.0
description: Generate x402 v2 payment middleware and route handlers for agent commerce

# Trigger patterns - when this skill should activate
triggers:
  - "/beacon-pay"
  - "enable payments on my API"
  - "add x402 middleware"
  - "accept payment for this endpoint"
  - "set up agent payments"
  - "generate payment middleware"
  - "configure subsidy for agents"
  - "monetize my API with x402"

# Natural language examples for intent matching
examples:
  - context: "User building paid API service"
    user_says: "I want to charge 1 token for each image generation request"
    agent_action: "Launch accepting-payments to generate x402 middleware with pricing and rate limits"
  - context: "User configuring subsidy"
    user_says: "Set up payment verification with 50% subsidy"
    agent_action: "Launch accepting-payments to create middleware with subsidy configuration and lifecycle hooks"
  - context: "User implementing x402 protocol"
    user_says: "Add payment verification to my Next.js API routes"
    agent_action: "Launch accepting-payments to wrap route handlers with x402 middleware and rate limiting"

# Domain hints for proactive suggestion
domain_hints:
  - x402
  - payments
  - middleware
  - blockchain
  - agent-commerce
  - subsidy
  - rate-limiting
  - monetization
  - token-payments

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: moderate
  effort_hint: large
  downgrade_allowed: false
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: false
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
  - AskUserQuestion

categories:
  - operations

inputExamples:
  - "/beacon-pay"
  - "/beacon-pay --endpoint /api/generate-image"
  - "/beacon-pay --subsidy 50%"

outputs:
  - name: middleware
    path: lib/x402/middleware.ts
    format: detailed
  - name: ratelimit
    path: lib/x402/ratelimit.ts
    format: detailed
  - name: hooks
    path: lib/x402/hooks.ts
    format: detailed
  - name: state
    path: grimoires/beacon/state.yaml
    format: summary

environment:
  optional:
    - FACILITATOR_URL
    - SUBSIDY_PROVIDER_ADDRESS
