name: diagramming-states
slug: diagramming-states
version: 1.0.0
description: |
  Use this skill IF user needs to visualize user journeys as state machines,
  OR wants to create diagrams for testing documentation,
  OR needs dual diagrams comparing expectations vs reality,
  OR is preparing journeys for test generation.
  Generates Mermaid state diagrams with selector mappings for Playwright testing.

# Trigger patterns - when this skill should activate
triggers:
  - "/diagram"
  - "create state diagram"
  - "visualize this journey"
  - "generate flow diagram"
  - "show me the states"
  - "diagram the flow"
  - "map this journey"

# Natural language examples for intent matching
examples:
  - context: "User has journey and needs visualization"
    user_says: "Can you create a state diagram for the deposit flow?"
    agent_action: "Launch diagramming-states to convert journey into Mermaid state machine"
  - context: "User wants rendered visual output"
    user_says: "Generate a diagram for rewards flow and render it as SVG"
    agent_action: "Launch diagramming-states with --render flag to create diagram and invoke beautiful-mermaid"
  - context: "User analyzing gaps between expectations and code"
    user_says: "Show me a comparison of what users expect vs what the code does"
    agent_action: "Launch diagramming-states with --with-reality flag to generate dual-sided diagram with gap annotations"
  - context: "User preparing for test generation"
    user_says: "I need a diagram with selectors for the withdrawal journey"
    agent_action: "Launch diagramming-states to create state machine with selector mapping table"

# Domain hints for proactive suggestion
domain_hints:
  - diagram
  - visualization
  - state
  - flow
  - journey
  - mermaid
  - mapping

entry: SKILL.md

capabilities:
  model_tier: sonnet
  danger_level: safe
  effort_hint: medium
  downgrade_allowed: true
  execution_hint: sequential
  requires:
    native_runtime: true
    tool_calling: true
    thinking_traces: false
    vision: false

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Edit
  - Skill
