/**
 * Development Setup Script
 *
 * One-command setup for local development environment.
 * - Creates .env from .env.example if missing
 * - Generates JWT keys if not configured
 * - Runs database migrations (graceful failure)
 * - Seeds category data (graceful failure)
 *
 * Usage: pnpm dev:setup
 *
 * @see sdd-local-dev-dx.md §3.6 dev-setup.ts
 * @see prd-local-dev-dx.md FR-4: One-Command Setup Script
 */

import { existsSync, copyFileSync, readFileSync, appendFileSync } from 'fs';
import { generateKeyPairSync } from 'crypto';
import { execSync } from 'child_process';
import { resolve } from 'path';

// ANSI colors for terminal output
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
};

function log(message: string, color: keyof typeof colors = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function logStep(step: number, total: number, message: string) {
  console.log(`\n${colors.cyan}[${step}/${total}]${colors.reset} ${message}`);
}

function logSuccess(message: string) {
  console.log(`${colors.green}✓${colors.reset} ${message}`);
}

function logWarning(message: string) {
  console.log(`${colors.yellow}⚠${colors.reset} ${message}`);
}

function logError(message: string) {
  console.log(`${colors.red}✗${colors.reset} ${message}`);
}

async function setup() {
  const envFile = resolve(process.cwd(), '.env');
  const envExampleFile = resolve(process.cwd(), '.env.example');

  console.log('\n╔══════════════════════════════════════════════════════════╗');
  console.log('║          Loa Constructs API - Development Setup          ║');
  console.log('╚══════════════════════════════════════════════════════════╝\n');

  const totalSteps = 4;

  // Step 1: Create .env file
  logStep(1, totalSteps, 'Checking environment file...');

  if (!existsSync(envFile)) {
    if (!existsSync(envExampleFile)) {
      logError('.env.example not found. Cannot create .env file.');
      process.exit(1);
    }
    copyFileSync(envExampleFile, envFile);
    logSuccess('Created .env from .env.example');
  } else {
    logSuccess('.env already exists (skipping)');
  }

  // Step 2: Generate JWT keys if not present
  logStep(2, totalSteps, 'Checking JWT keys...');

  let envContent = readFileSync(envFile, 'utf-8');

  // Check if JWT_PRIVATE_KEY is configured (not empty)
  const hasPrivateKey =
    envContent.includes('JWT_PRIVATE_KEY=') &&
    !envContent.match(/JWT_PRIVATE_KEY=\s*($|\n)/);
  const hasPublicKey =
    envContent.includes('JWT_PUBLIC_KEY=') &&
    !envContent.match(/JWT_PUBLIC_KEY=\s*($|\n)/);

  if (!hasPrivateKey || !hasPublicKey) {
    log('Generating RSA-2048 key pair...', 'dim');

    const { publicKey, privateKey } = generateKeyPairSync('rsa', {
      modulusLength: 2048,
      publicKeyEncoding: { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    });

    const keyId = `key-${new Date().toISOString().slice(0, 7)}`;
    const privateKeyBase64 = Buffer.from(privateKey).toString('base64');
    const publicKeyBase64 = Buffer.from(publicKey).toString('base64');

    const keysToAppend = `
# =============================================================================
# JWT Keys (Auto-generated by dev:setup)
# =============================================================================
JWT_PRIVATE_KEY=${privateKeyBase64}
JWT_PUBLIC_KEY=${publicKeyBase64}
JWT_KEY_ID=${keyId}
`;

    appendFileSync(envFile, keysToAppend);
    logSuccess(`JWT keys generated and added to .env (${keyId})`);
  } else {
    logSuccess('JWT keys already configured (skipping)');
  }

  // Step 3: Run database migrations
  logStep(3, totalSteps, 'Running database migrations...');

  try {
    execSync('pnpm db:migrate', {
      stdio: 'inherit',
      cwd: process.cwd(),
    });
    logSuccess('Migrations applied');
  } catch (error) {
    logWarning('Migration failed (database may not be available)');
    log('You can run with mock database: pnpm dev:mock', 'dim');
  }

  // Step 4: Seed categories
  logStep(4, totalSteps, 'Seeding category data...');

  try {
    execSync('pnpm db:seed:categories', {
      stdio: 'inherit',
      cwd: process.cwd(),
    });
    logSuccess('Categories seeded');
  } catch (error) {
    logWarning('Seeding failed (database may not be available)');
  }

  // Final message
  console.log('\n╔══════════════════════════════════════════════════════════╗');
  console.log('║                    Setup Complete!                       ║');
  console.log('╚══════════════════════════════════════════════════════════╝');
  console.log('\nNext steps:');
  console.log(`  ${colors.cyan}pnpm dev${colors.reset}        Start with database`);
  console.log(`  ${colors.cyan}pnpm dev:mock${colors.reset}   Start without database (mock mode)\n`);
}

// Run setup
setup().catch((error) => {
  logError(`Unexpected error: ${error.message}`);
  process.exit(1);
});
