name: analyzing-feedback
slug: analyzing-feedback
version: 1.0.0
description: |
  Use this skill IF user wants to analyze feedback patterns from design iterations,
  OR wants to see what design preferences have emerged,
  OR needs to detect patterns for taste learning.
  Analyzes JSONL logs and auto-contributes high-confidence patterns upstream.

# Trigger patterns - when this skill should activate
triggers:
  - "/artisan-patterns"
  - "analyze feedback patterns"
  - "what patterns have emerged"
  - "show me my design preferences"
  - "detect patterns"
  - "feedback analysis"
  - "what do I prefer"

# Natural language examples for intent matching
examples:
  - context: "User wants to see patterns"
    user_says: "What design patterns have emerged from my feedback?"
    agent_action: "Launch analyzing-feedback to parse logs and generate patterns.md"
  - context: "User curious about preferences"
    user_says: "Have I been consistent in my design choices?"
    agent_action: "Launch analyzing-feedback to calculate consistency across sessions"
  - context: "After many iterations"
    user_says: "I've done a lot of design iteration, what have I learned?"
    agent_action: "Launch analyzing-feedback to extract high-confidence patterns"
  - context: "Checking for upstream contribution"
    user_says: "Are there any patterns ready to contribute upstream?"
    agent_action: "Launch analyzing-feedback to identify HIGH confidence patterns"

# Domain hints for proactive suggestion
domain_hints:
  - design
  - patterns
  - feedback
  - learning
  - preferences

entry: SKILL.md

allowed-tools:
  - Read
  - Write
  - Glob
  - Grep
  - Bash

dependencies:
  - artifact: "grimoires/artisan/feedback/*.jsonl"
    required: true
    description: "Feedback logs from design iteration sessions"

outputs:
  - path: "grimoires/artisan/feedback/patterns.md"
    description: "Detected patterns with confidence levels"
